# Directories arguments
#data_dir: "full_cityscapes_res"
data_dir: "simple_lyft_data"
exp_dir:  "unet_mobilenet"
out_dir:  "unet_mobilenet"
checkpoint_dir: "unet_mobilenet"

# Data arguments
#img_height:   512
#img_width:    1024
#num_channels: 3
#num_classes:  20
img_height:   600
img_width:    800
num_channels: 3
num_classes:  3

# Train arguments
#num_epochs: 200
num_epochs: 2
batch_size: 5
shuffle: True
data_mode: "experiment"
save_every: 5
test_every: 5
max_to_keep: 2
weighted_loss: True
random_cropping: False
freeze_encoder: False

# Models arguments
learning_rate:   0.0001
weight_decay: 0.0005
bias : 0.0
batchnorm_enabled: True
pretrained_path: "pretrained_weights/mobilenet_v1.pkl"

# Misc arguments
verbose: False

